package com.futureme.shared.lifeevents

import com.futureme.shared.models.FinancialProfile
import com.futureme.shared.models.LifeEventPlan
import com.futureme.shared.models.LifeEventType

class LifeEventPlanner {
    fun plans(profile: FinancialProfile): List<LifeEventPlan> = listOf(
        plan(
            id = "event-baby",
            type = LifeEventType.NEW_BABY,
            title = "Welcome a new baby",
            subtitle = "Plan leave, healthcare, supplies, and childcare.",
            monthly = 2_150.0,
            low = 8_000.0,
            high = 18_000.0,
            risk = 14,
            steps = listOf("Build a family transition fund", "Confirm leave benefits", "Model childcare start dates"),
            insights = listOf("Childcare is the largest recurring cost", "Emergency runway remains the key readiness measure"),
            scenarios = listOf("have-a-child"),
        ),
        plan(
            "event-home",
            LifeEventType.HOME_PURCHASE,
            "Purchase a home",
            "Test down payment, mortgage, maintenance, and liquidity.",
            2_250.0,
            75_000.0,
            155_000.0,
            18,
            listOf("Clear high-interest debt", "Preserve six months of reserves", "Budget 1% annually for maintenance"),
            listOf("A $700K purchase materially reduces liquidity"),
            listOf("buy-home", "wait-to-buy"),
        ),
        plan(
            "event-relocation",
            LifeEventType.RELOCATION,
            "Relocate to another state",
            "Compare compensation, housing, taxes, and support networks.",
            -1_250.0,
            10_000.0,
            22_000.0,
            3,
            listOf("Confirm net compensation", "Price housing before committing", "Reserve transition costs"),
            listOf("Lower recurring housing can improve the five-year outlook"),
            listOf("move-to-texas", "stay-in-new-jersey"),
        ),
        plan(
            "event-job-loss",
            LifeEventType.JOB_LOSS,
            "Prepare for job loss",
            "Stress-test reserves against a six-month income interruption.",
            -profile.monthlyNetIncome,
            0.0,
            8_000.0,
            24,
            listOf("Maintain essential-expense runway", "Review severance and insurance", "Predefine expense cuts"),
            listOf("Liquidity matters more than net worth during an income shock"),
            listOf("job-loss"),
        ),
        plan(
            "event-parent",
            LifeEventType.PARENT_SUPPORT,
            "Support an aging parent",
            "Prepare for recurring support and care coordination.",
            1_200.0,
            3_000.0,
            15_000.0,
            10,
            listOf("Clarify expected duration", "Review tax and benefits options", "Create a dedicated support reserve"),
            listOf("Support should not rely on revolving debt"),
            listOf("invest-more"),
        ),
        plan(
            "event-medical",
            LifeEventType.MAJOR_MEDICAL_EXPENSE,
            "Absorb a major medical expense",
            "Model deductibles, leave, and recovery costs.",
            450.0,
            8_000.0,
            30_000.0,
            16,
            listOf("Confirm out-of-pocket maximum", "Preserve HSA funds", "Keep accessible cash separate"),
            listOf("Medical risk can combine one-time and temporary monthly costs"),
            listOf("job-loss"),
        ),
    )

    private fun plan(
        id: String,
        type: LifeEventType,
        title: String,
        subtitle: String,
        monthly: Double,
        low: Double,
        high: Double,
        risk: Int,
        steps: List<String>,
        insights: List<String>,
        scenarios: List<String>,
    ) = LifeEventPlan(
        id = id,
        type = type,
        title = title,
        subtitle = subtitle,
        estimatedMonthlyImpact = monthly,
        oneTimeCostLow = low,
        oneTimeCostHigh = high,
        riskImpact = risk,
        recommendedPreparationSteps = steps,
        relatedInsights = insights,
        suggestedScenarioIds = scenarios,
    )
}
